name: Builds

on: [push, pull_request]

jobs:
  fmt:
    runs-on: windows-latest
    name: fmt
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up rust
        run: rustup default nightly

      - name: cargo fmt
        run: cargo +nightly fmt --check

  clippy:
    name: clippy
    runs-on: windows-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up rust
        run: rustup default stable

      - name: cargo clippy
        env:
          RUSTFLAGS: "-Dwarnings"
        run: cargo clippy

  build:
    runs-on: windows-latest
    name: check & test
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up rust
        run: rustup default stable

      - name: cargo check
        run: cargo check

      - name: cargo test
        run: cargo test
